### ISSUE TITLE
choosing config.yml

### ISSUE THREAD

**Issue by lucasart** [Heiaha/Hermod#16]
I want to run several bots, without the hassle of duplicating the whole thing for each bot. Like this:
```
$ python main.py --config bot1.yml &> bot1.log &
$ python main.py --config bot2.yml &> bot2.log &
```
What do you think?

**Comment by Heiaha** [comment]
Sure, this had been on my mind at one point as well. Added with https://github.com/Heiaha/asyncLio-bot/pull/17.
