### ISSUE TITLE
should_use_book(): unexpected ply count

### ISSUE THREAD

**Issue by lucasart** [Heiaha/Hermod#19]
For example if depth=0, white gets one book move, black none. Should be `<` not `<=`.

In fact it's very confusing to use plies instead of full moves which is what most users expect. I can't see a reason for using an odd number

**Comment by Heiaha** [comment]
Sure, makes enough sense. Updated in https://github.com/Heiaha/asyncLio-bot/commit/f82d45fbd8881401bf0fa812f2f5629a0d8292ec.
