### ISSUE TITLE
time losses

### ISSUE THREAD

**Issue by lucasart** [Heiaha/Hermod#21]
Having problems after updating from GitHub:
* f82d45f is ok
* d7ddd2f leads to frequent time losses (just hangs randomly)

Note that I run 3 bots in parallel, each running up to 4 concurrent games. Tried disabling concurrency 1 with d7ddd2f, still frequent time losses.

**Comment by Heiaha** [comment]
Hi, not sure exactly what could be causing the hanging. When you updated, did you also update your config file to include the "max_rating_diffs" section from [here](https://github.com/Heiaha/asyncLio-bot/commit/56ad9e369076d944eebe8b886ee39bfa46e162a5?diff=unified&w=1)?

**Comment by lucasart** [comment]
I've reduced the problem to a single patch: a6ef1ca

And then verified by moving to the top of master branch, and reverting the patch from there, all is good.

This means that it's `httpx 0.27` that causes the problem. At least on my setup: Termux on Android.

Edit: spoke too soon. The undeterministic nature of the problem makes it hard to bissect. Nothing useful in the logs, the engine seems to just lose on time without ever having been asked by the interface to do anything. Just after book moves are played.

**Comment by lucasart** [comment]
Ok. Seems fine now with the master branch as is. Not sure what I did wrong before, but suspect this venv update process that I'm not familiar with.
